import "styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Provider } from "react-redux";
import { store } from "@/app/store";
import { userObserver } from "@/auth/firebase";
import { useAppDispatch } from "@/app/hooks";

interface Imetadata {
  title: string;
  description: string;
}
export const metadata: Imetadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function App({ Component, pageProps }: AppProps) {
  
  return (
    <Provider store={store}>
      <Head>
        <title>{metadata.title}</title>
        <link rel="shortcut icon" href="vercel.svg" type="image/x-icon" />
      </Head>
      <Component {...pageProps} />
    </Provider>
  );
}
